import {TRPCError} from '@trpc/server'
import {z} from 'zod'
import type {StudioRoleType} from '@play/supabase-client'
import {StudioRole} from '@play/supabase-client'
import {protectedProcedure, router} from '../index'
import {AuditAction, logAuditEvent} from '../lib/audit'
import {
  RATE_LIMIT_CONFIGS,
  getRateLimitKey,
  isRateLimited,
} from '../lib/rate-limit'

// Roles that can manage invites
const MANAGE_ROLES: StudioRoleType[] = [StudioRole.OWNER, StudioRole.ADMIN]

export const inviteRouter = router({
  /**
   * List pending invites for a studio
   */
  list: protectedProcedure
    .input(z.object({studioId: z.string().uuid()}))
    .query(async ({ctx, input}) => {
      const {user, supabase} = ctx

      // Check user is OWNER or ADMIN of studio
      const {data: member} = await supabase
        .from('studio_members')
        .select('role')
        .eq('studio_id', input.studioId)
        .eq('user_id', user.id)
        .single()

      if (!member || !MANAGE_ROLES.includes(member.role as StudioRoleType)) {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'You do not have permission to view invites',
        })
      }

      const {data: invites, error} = await supabase
        .from('invites')
        .select('id, email, role, created_at, accepted_at')
        .eq('studio_id', input.studioId)
        .is('accepted_at', null)
        .order('created_at', {ascending: false})

      if (error) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: error.message,
        })
      }

      return invites || []
    }),

  /**
   * Create an invite to a studio
   */
  create: protectedProcedure
    .input(
      z.object({
        studioId: z.string().uuid(),
        email: z.string().email(),
        role: z.enum(['OWNER', 'ADMIN', 'MEMBER']).default('MEMBER'),
      }),
    )
    .mutation(async ({ctx, input}) => {
      const {user, supabase} = ctx

      // Rate limit invite creation
      if (
        isRateLimited(
          getRateLimitKey(user.id, 'invite.create'),
          RATE_LIMIT_CONFIGS.invites,
        )
      ) {
        throw new TRPCError({
          code: 'TOO_MANY_REQUESTS',
          message: 'Too many invites sent. Please wait a moment.',
        })
      }

      // Check user is OWNER or ADMIN of studio
      const {data: member} = await supabase
        .from('studio_members')
        .select('role')
        .eq('studio_id', input.studioId)
        .eq('user_id', user.id)
        .single()

      if (!member || !MANAGE_ROLES.includes(member.role as StudioRoleType)) {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'You do not have permission to invite users',
        })
      }

      // Only owners can invite as owner
      if (input.role === 'OWNER' && member.role !== StudioRole.OWNER) {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'Only owners can invite other owners',
        })
      }

      // Check if there's already a pending invite for this email
      const {data: existingInvite} = await supabase
        .from('invites')
        .select('id')
        .eq('studio_id', input.studioId)
        .eq('email', input.email)
        .is('accepted_at', null)
        .single()

      if (existingInvite) {
        throw new TRPCError({
          code: 'CONFLICT',
          message: 'An invite for this email is already pending',
        })
      }

      // Check if user is already a member
      const {data: existingMember} = await supabase
        .from('profiles')
        .select('user_id')
        .eq('email', input.email)
        .single()

      if (existingMember) {
        const {data: isMember} = await supabase
          .from('studio_members')
          .select('user_id')
          .eq('studio_id', input.studioId)
          .eq('user_id', existingMember.user_id)
          .single()

        if (isMember) {
          throw new TRPCError({
            code: 'CONFLICT',
            message: 'This user is already a member of the studio',
          })
        }
      }

      // Create invite (token is auto-generated by DB)
      const {data: invite, error} = await supabase
        .from('invites')
        .insert({
          studio_id: input.studioId,
          email: input.email,
          role: input.role,
        })
        .select()
        .single()

      if (error) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: error.message,
        })
      }

      await logAuditEvent(supabase, {
        userId: user.id,
        userEmail: user.email,
        action: AuditAction.INVITE_CREATE,
        studioId: input.studioId,
        targetType: 'invite',
        targetId: String(invite.id),
        metadata: {invitedEmail: input.email, role: input.role},
      })

      // TODO: Send email with invite link containing token

      return invite
    }),

  /**
   * Accept an invite using the token
   */
  accept: protectedProcedure
    .input(z.object({token: z.string().uuid()}))
    .mutation(async ({ctx, input}) => {
      const {user, supabase} = ctx

      // Get the invite
      const {data: invite, error: inviteError} = await supabase
        .from('invites')
        .select('id, studio_id, email, role, accepted_at, expires_at')
        .eq('token', input.token)
        .single()

      if (inviteError || !invite) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Invite not found or has expired',
        })
      }

      if (invite.accepted_at) {
        throw new TRPCError({
          code: 'BAD_REQUEST',
          message: 'This invite has already been accepted',
        })
      }

      // Check if invite has expired
      if (invite.expires_at && new Date(invite.expires_at) < new Date()) {
        throw new TRPCError({
          code: 'BAD_REQUEST',
          message: 'This invite has expired',
        })
      }

      // Verify the email matches the user
      const {data: profile} = await supabase
        .from('profiles')
        .select('email')
        .eq('user_id', user.id)
        .single()

      if (
        !profile ||
        profile.email.toLowerCase() !== invite.email.toLowerCase()
      ) {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'This invite was sent to a different email address',
        })
      }

      // Check if already a member
      const {data: existingMember} = await supabase
        .from('studio_members')
        .select('user_id')
        .eq('studio_id', invite.studio_id)
        .eq('user_id', user.id)
        .single()

      if (existingMember) {
        // Mark invite as accepted anyway
        await supabase
          .from('invites')
          .update({accepted_at: new Date().toISOString()})
          .eq('id', invite.id)

        throw new TRPCError({
          code: 'CONFLICT',
          message: 'You are already a member of this studio',
        })
      }

      // Add user to studio
      const {error: memberError} = await supabase
        .from('studio_members')
        .insert({
          studio_id: invite.studio_id,
          user_id: user.id,
          role: invite.role,
        })

      if (memberError) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: memberError.message,
        })
      }

      // Mark invite as accepted
      await supabase
        .from('invites')
        .update({accepted_at: new Date().toISOString()})
        .eq('id', invite.id)

      await logAuditEvent(supabase, {
        userId: user.id,
        userEmail: user.email,
        action: AuditAction.INVITE_ACCEPT,
        studioId: invite.studio_id,
        targetType: 'invite',
        targetId: String(invite.id),
        metadata: {role: invite.role},
      })

      return {success: true, studioId: invite.studio_id}
    }),

  /**
   * Delete/revoke an invite
   */
  delete: protectedProcedure
    .input(z.object({id: z.number()}))
    .mutation(async ({ctx, input}) => {
      const {user, supabase} = ctx

      // Get the invite to check studio
      const {data: invite, error: inviteError} = await supabase
        .from('invites')
        .select('studio_id')
        .eq('id', input.id)
        .single()

      if (inviteError || !invite) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Invite not found',
        })
      }

      // Check user is OWNER or ADMIN of studio
      const {data: member} = await supabase
        .from('studio_members')
        .select('role')
        .eq('studio_id', invite.studio_id)
        .eq('user_id', user.id)
        .single()

      if (!member || !MANAGE_ROLES.includes(member.role as StudioRoleType)) {
        throw new TRPCError({
          code: 'FORBIDDEN',
          message: 'You do not have permission to delete invites',
        })
      }

      const {error} = await supabase.from('invites').delete().eq('id', input.id)

      if (error) {
        throw new TRPCError({
          code: 'INTERNAL_SERVER_ERROR',
          message: error.message,
        })
      }

      await logAuditEvent(supabase, {
        userId: user.id,
        userEmail: user.email,
        action: AuditAction.INVITE_REVOKE,
        studioId: invite.studio_id,
        targetType: 'invite',
        targetId: String(input.id),
      })

      return {success: true}
    }),

  /**
   * Get invite details by token (public info for accepting)
   */
  getByToken: protectedProcedure
    .input(z.object({token: z.string().uuid()}))
    .query(async ({ctx, input}) => {
      const {supabase} = ctx

      const {data: invite, error} = await supabase
        .from('invites')
        .select(
          `
          id,
          email,
          role,
          accepted_at,
          studios (
            id,
            slug,
            name,
            avatar_url
          )
        `,
        )
        .eq('token', input.token)
        .single()

      if (error || !invite) {
        throw new TRPCError({
          code: 'NOT_FOUND',
          message: 'Invite not found',
        })
      }

      return invite
    }),
})
